# Generated by Django 5.1 on 2024-08-14 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='doctors',
            field=models.ManyToManyField(blank=True, null=True, related_name='department_as_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='patients',
            field=models.ManyToManyField(blank=True, null=True, related_name='department_as_patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
